# SonarCloud project details
sonar.projectKey=CDDOUI
sonar.organization=agrimetrics
sonar.host.url=https://sonarcloud.io

# Language
sonar.language=cs

# Exclude test projects from analysis
sonar.exclusions=**/*.sqlproj,**/Tests/**,**/Test/**,**/*Tests.cs,**/bin/**,**/obj/**

# Exclude test files from coverage reports
sonar.test.exclusions=**/*Test.cs,**/Tests/**,**/*Tests.cs,**/cddo-users.test/**

# Encoding
sonar.sourceEncoding=UTF-8
