namespace Cddo.Data.Marketplace.UI.Model.Countries;

internal class CountrySelectionPresenter : ICountrySelectionPresenter
{
    #region Non Uk Country Selections
    private static readonly List<ICountrySelection> nonUkCountrySelections =
        [
            CreateCountrySelection("afghanistan", "Afghanistan"),
            CreateCountrySelection("albania", "Albania"),
            CreateCountrySelection("algeria", "Algeria"),
            CreateCountrySelection("andorra", "Andorra"),
            CreateCountrySelection("angola", "Angola"),
            CreateCountrySelection("anguilla", "Anguilla"),
            CreateCountrySelection("antigua-and-barbuda", "Antigua and Barbuda"),
            CreateCountrySelection("argentina", "Argentina"),
            CreateCountrySelection("armenia", "Armenia"),
            CreateCountrySelection("aruba", "Aruba"),
            CreateCountrySelection("australia", "Australia"),
            CreateCountrySelection("austria", "Austria"),
            CreateCountrySelection("azerbaijan", "Azerbaijan"),
            CreateCountrySelection("bahamas", "Bahamas"),
            CreateCountrySelection("bahrain", "Bahrain"),
            CreateCountrySelection("bangladesh", "Bangladesh"),
            CreateCountrySelection("barbados", "Barbados"),
            CreateCountrySelection("belarus", "Belarus"),
            CreateCountrySelection("belgium", "Belgium"),
            CreateCountrySelection("belize", "Belize"),
            CreateCountrySelection("benin", "Benin"),
            CreateCountrySelection("bermuda", "Bermuda"),
            CreateCountrySelection("bhutan", "Bhutan"),
            CreateCountrySelection("bolivia", "Bolivia"),
            CreateCountrySelection("bonaire-st-eustatius-saba", "Bonaire/St Eustatius/Saba"),
            CreateCountrySelection("bosnia-and-herzegovina", "Bosnia and Herzegovina"),
            CreateCountrySelection("botswana", "Botswana"),
            CreateCountrySelection("brazil", "Brazil"),
            CreateCountrySelection("british-virgin-islands", "British Virgin Islands"),
            CreateCountrySelection("british-dependent-territories-citizen", "British dependent territories citizen"),
            CreateCountrySelection("british-national-overseas", "British national overseas"),
            CreateCountrySelection("british-overseas-citizen", "British overseas citizen"),
            CreateCountrySelection("british-protected-person", "British protected person"),
            CreateCountrySelection("brunei", "Brunei"),
            CreateCountrySelection("bulgaria", "Bulgaria"),
            CreateCountrySelection("burkina-faso", "Burkina Faso"),
            CreateCountrySelection("burundi", "Burundi"),
            CreateCountrySelection("cambodia", "Cambodia"),
            CreateCountrySelection("cameroon", "Cameroon"),
            CreateCountrySelection("canada", "Canada"),
            CreateCountrySelection("cape-verde", "Cape Verde"),
            CreateCountrySelection("cayman-islands", "Cayman Islands"),
            CreateCountrySelection("central-african-republic", "Central African Republic"),
            CreateCountrySelection("chad", "Chad"),
            CreateCountrySelection("chile", "Chile"),
            CreateCountrySelection("china", "China"),
            CreateCountrySelection("colombia", "Colombia"),
            CreateCountrySelection("comoros", "Comoros"),
            CreateCountrySelection("congo", "Congo"),
            CreateCountrySelection("costa-rica", "Costa Rica"),
            CreateCountrySelection("cote-d-ivoire", "Cote d’Ivoire"),
            CreateCountrySelection("croatia", "Croatia"),
            CreateCountrySelection("cuba", "Cuba"),
            CreateCountrySelection("curacao", "Curaçao"),
            CreateCountrySelection("cyprus", "Cyprus"),
            CreateCountrySelection("cyprus-north", "Cyprus (northern part of Cyprus)"),
            CreateCountrySelection("czech-republic", "Czech Republic"),
            CreateCountrySelection("democratic-republic-of-the-congo", "Democratic Republic of the Congo"),
            CreateCountrySelection("denmark", "Denmark"),
            CreateCountrySelection("djibouti", "Djibouti"),
            CreateCountrySelection("dominica", "Dominica"),
            CreateCountrySelection("dominican-republic", "Dominican Republic"),
            CreateCountrySelection("ecuador", "Ecuador"),
            CreateCountrySelection("egypt", "Egypt"),
            CreateCountrySelection("el-salvador", "El Salvador"),
            CreateCountrySelection("equatorial-guinea", "Equatorial Guinea"),
            CreateCountrySelection("eritrea", "Eritrea"),
            CreateCountrySelection("estonia", "Estonia"),
            CreateCountrySelection("eswatini", "Eswatini"),
            CreateCountrySelection("ethiopia", "Ethiopia"),
            CreateCountrySelection("falkland-islands", "Falkland Islands"),
            CreateCountrySelection("federated-states-of-micronesia", "Federated States of Micronesia"),
            CreateCountrySelection("fiji", "Fiji"),
            CreateCountrySelection("finland", "Finland"),
            CreateCountrySelection("france", "France"),
            CreateCountrySelection("gabon", "Gabon"),
            CreateCountrySelection("the-gambia", "The Gambia"),
            CreateCountrySelection("georgia", "Georgia"),
            CreateCountrySelection("germany", "Germany"),
            CreateCountrySelection("ghana", "Ghana"),
            CreateCountrySelection("greece", "Greece"),
            CreateCountrySelection("grenada", "Grenada"),
            CreateCountrySelection("guatemala", "Guatemala"),
            CreateCountrySelection("guinea", "Guinea"),
            CreateCountrySelection("guinea-bissau", "Guinea-Bissau"),
            CreateCountrySelection("guyana", "Guyana"),
            CreateCountrySelection("haiti", "Haiti"),
            CreateCountrySelection("honduras", "Honduras"),
            CreateCountrySelection("hong-kong", "Hong Kong"),
            CreateCountrySelection("hong-kong-(british-national-overseas)", "Hong Kong (British national overseas)"),
            CreateCountrySelection("hungary", "Hungary"),
            CreateCountrySelection("iceland", "Iceland"),
            CreateCountrySelection("india", "India"),
            CreateCountrySelection("indonesia", "Indonesia"),
            CreateCountrySelection("iran", "Iran"),
            CreateCountrySelection("iraq", "Iraq"),
            CreateCountrySelection("ireland", "Ireland"),
            CreateCountrySelection("israel", "Israel"),
            CreateCountrySelection("italy", "Italy"),
            CreateCountrySelection("jamaica", "Jamaica"),
            CreateCountrySelection("japan", "Japan"),
            CreateCountrySelection("jordan", "Jordan"),
            CreateCountrySelection("kazakhstan", "Kazakhstan"),
            CreateCountrySelection("kenya", "Kenya"),
            CreateCountrySelection("kiribati", "Kiribati"),
            CreateCountrySelection("kosovo", "Kosovo"),
            CreateCountrySelection("kuwait", "Kuwait"),
            CreateCountrySelection("kyrgyzstan", "Kyrgyzstan"),
            CreateCountrySelection("laos", "Laos"),
            CreateCountrySelection("latvia", "Latvia"),
            CreateCountrySelection("lebanon", "Lebanon"),
            CreateCountrySelection("lesotho", "Lesotho"),
            CreateCountrySelection("liberia", "Liberia"),
            CreateCountrySelection("libya", "Libya"),
            CreateCountrySelection("liechtenstein", "Liechtenstein"),
            CreateCountrySelection("lithuania", "Lithuania"),
            CreateCountrySelection("luxembourg", "Luxembourg"),
            CreateCountrySelection("macao", "Macao"),
            CreateCountrySelection("madagascar", "Madagascar"),
            CreateCountrySelection("malawi", "Malawi"),
            CreateCountrySelection("malaysia", "Malaysia"),
            CreateCountrySelection("maldives", "Maldives"),
            CreateCountrySelection("mali", "Mali"),
            CreateCountrySelection("malta", "Malta"),
            CreateCountrySelection("marshall-islands", "Marshall Islands"),
            CreateCountrySelection("mauritania", "Mauritania"),
            CreateCountrySelection("mauritius", "Mauritius"),
            CreateCountrySelection("mexico", "Mexico"),
            CreateCountrySelection("moldova", "Moldova"),
            CreateCountrySelection("monaco", "Monaco"),
            CreateCountrySelection("mongolia", "Mongolia"),
            CreateCountrySelection("montenegro", "Montenegro"),
            CreateCountrySelection("montserrat", "Montserrat"),
            CreateCountrySelection("morocco", "Morocco"),
            CreateCountrySelection("mozambique", "Mozambique"),
            CreateCountrySelection("myanmar", "Myanmar"),
            CreateCountrySelection("namibia", "Namibia"),
            CreateCountrySelection("nauru", "Nauru"),
            CreateCountrySelection("nepal", "Nepal"),
            CreateCountrySelection("netherlands", "Netherlands"),
            CreateCountrySelection("new-zealand", "New Zealand"),
            CreateCountrySelection("nicaragua", "Nicaragua"),
            CreateCountrySelection("niger", "Niger"),
            CreateCountrySelection("nigeria", "Nigeria"),
            CreateCountrySelection("north-korea", "North Korea"),
            CreateCountrySelection("north-macedonia", "North Macedonia"),
            CreateCountrySelection("norway", "Norway"),
            CreateCountrySelection("oman", "Oman"),
            CreateCountrySelection("pakistan", "Pakistan"),
            CreateCountrySelection("palau", "Palau"),
            CreateCountrySelection("palestinian-territories", "Palestinian Territories"),
            CreateCountrySelection("panama", "Panama"),
            CreateCountrySelection("papua-new-guinea", "Papua New Guinea"),
            CreateCountrySelection("paraguay", "Paraguay"),
            CreateCountrySelection("peru", "Peru"),
            CreateCountrySelection("philippines", "Philippines"),
            CreateCountrySelection("pitcairn-island", "Pitcairn Island"),
            CreateCountrySelection("poland", "Poland"),
            CreateCountrySelection("portugal", "Portugal"),
            CreateCountrySelection("qatar", "Qatar"),
            CreateCountrySelection("romania", "Romania"),
            CreateCountrySelection("russia", "Russia"),
            CreateCountrySelection("rwanda", "Rwanda"),
            CreateCountrySelection("saint-barthelemy", "Saint-Barthélemy"),
            CreateCountrySelection("samoa", "Samoa"),
            CreateCountrySelection("san-marino", "San Marino"),
            CreateCountrySelection("saudi-arabia", "Saudi Arabia"),
            CreateCountrySelection("senegal", "Senegal"),
            CreateCountrySelection("serbia", "Serbia"),
            CreateCountrySelection("seychelles", "Seychelles"),
            CreateCountrySelection("sierra-leone", "Sierra Leone"),
            CreateCountrySelection("singapore", "Singapore"),
            CreateCountrySelection("slovakia", "Slovakia"),
            CreateCountrySelection("slovenia", "Slovenia"),
            CreateCountrySelection("solomon-islands", "Solomon Islands"),
            CreateCountrySelection("somalia", "Somalia"),
            CreateCountrySelection("south-africa", "South Africa"),
            CreateCountrySelection("south-georgia-and-the-south-sandwich-islands", "South Georgia and the South Sandwich Islands"),
            CreateCountrySelection("south-korea", "South Korea"),
            CreateCountrySelection("south-sudan", "South Sudan"),
            CreateCountrySelection("spain", "Spain"),
            CreateCountrySelection("sri-lanka", "Sri Lanka"),
            CreateCountrySelection("st-helena-ascension-and-tristan-da-cunha", "St Helena, Ascension and Tristan da Cunha"),
            CreateCountrySelection("st-kitts-and-nevis", "St Kitts and Nevis"),
            CreateCountrySelection("st-lucia", "St Lucia"),
            CreateCountrySelection("st-maarten", "St Maarten"),
            CreateCountrySelection("st-martin", "St Martin"),
            CreateCountrySelection("st-vincent-and-the-grenadines", "St Vincent and The Grenadines"),
            CreateCountrySelection("stateless-or-refugee", "Stateless or Refugee"),
            CreateCountrySelection("sudan", "Sudan"),
            CreateCountrySelection("suriname", "Suriname"),
            CreateCountrySelection("sweden", "Sweden"),
            CreateCountrySelection("switzerland", "Switzerland"),
            CreateCountrySelection("syria", "Syria"),
            CreateCountrySelection("sao-tome-and-principe", "São Tomé and Principe"),
            CreateCountrySelection("taiwan", "Taiwan"),
            CreateCountrySelection("tajikistan", "Tajikistan"),
            CreateCountrySelection("tanzania", "Tanzania"),
            CreateCountrySelection("thailand", "Thailand"),
            CreateCountrySelection("timor-leste", "Timor Leste"),
            CreateCountrySelection("togo", "Togo"),
            CreateCountrySelection("tonga", "Tonga"),
            CreateCountrySelection("trinidad-and-tobago", "Trinidad and Tobago"),
            CreateCountrySelection("tunisia", "Tunisia"),
            CreateCountrySelection("turkey", "Turkey"),
            CreateCountrySelection("turkmenistan", "Turkmenistan"),
            CreateCountrySelection("turks-and-caicos-islands", "Turks and Caicos Islands"),
            CreateCountrySelection("tuvalu", "Tuvalu"),
            CreateCountrySelection("usa", "USA"),
            CreateCountrySelection("uganda", "Uganda"),
            CreateCountrySelection("ukraine", "Ukraine"),
            CreateCountrySelection("united-arab-emirates", "United Arab Emirates"),
            CreateCountrySelection("uruguay", "Uruguay"),
            CreateCountrySelection("uzbekistan", "Uzbekistan"),
            CreateCountrySelection("vanuatu", "Vanuatu"),
            CreateCountrySelection("vatican-city", "Vatican City"),
            CreateCountrySelection("venezuela", "Venezuela"),
            CreateCountrySelection("vietnam", "Vietnam"),
            CreateCountrySelection("yemen", "Yemen"),
            CreateCountrySelection("zambia", "Zambia"),
            CreateCountrySelection("zimbabwe", "Zimbabwe")
        ];
    #endregion

    private static readonly List<ICountrySelection> countrySelectionsWithUnitedKingdom =
        new List<ICountrySelection>
        {
            CreateCountrySelection("united-kingdom", "United Kingdom")
        }.Concat(nonUkCountrySelections).ToList();

    public IEnumerable<ICountrySelection> CountrySelectionsWithUnitedKingdom => countrySelectionsWithUnitedKingdom;

    public IEnumerable<ICountrySelection> CountrySelectionsWithoutUnitedKingdom => nonUkCountrySelections;

    private static ICountrySelection CreateCountrySelection(
        string id,
        string countryName)
    {
        return new CountrySelection
        {
            Id = id,
            CountryName = countryName
        };
    }
}