namespace Cddo.Data.Marketplace.Audit
{
    public static class EventTypes
    {
        public enum AdminAuditEvent
        {
            AdminLogin = 1,
            AdminLogout = 2,
            AdminUserPermissionChange = 3,
            AdminAddUserToOrganization = 4,
            AdminRemoveUserFromOrganization = 5,
            AdminApproveUser = 6,
            AdminRejectUser = 7,
            AdminRoleChange = 8,
            AdminPasswordResetForUser = 9,
            AdminAccountCreation = 10,
            AdminAccountDeletion = 11,
            AdminAccountLockout = 12,
            AdminAccountUnlock = 13,
            AdminUserAccessOverride = 14,
            AdminPolicyUpdate = 15,
            AdminSystemSettingsUpdate = 16,
            AdminCreateOrganization = 17,
            AdminDeleteOrganization = 18,
            AdminUpdateOrganizationDetails = 19,
            AdminAuditLogAccess = 20,
            AdminAddUserToRole = 21,
            AdminRemoveUserFromRole = 22,
            AdminUploadCsv = 23,
            AdminDownloadTemplate = 24,
            AdminAddNewTitle = 25,
            AdminAddAlternativeTitle = 26,
            AdminAddNewDescription = 27,
            AdminAddNewSummary = 28,
            AdminAddNewIdentifier = 29,
            AdminAddNewThemes = 30,
            AdminAddNewKeywords = 31,
            AdminAddNewContactPoint = 32,
            AdminAddNewVersion = 33,
            AdminAddNewIssued = 34,
            AdminAddNewLicence = 35,
            AdminAddNewAccessRights = 36,
            AdminAddNewSecurityClassification = 37,
            AdminAddNewRelatedResource = 38,
            AdminAddNewServiceType = 39,
            AdminAddFrequency = 40,
            AdminAddSupplyFormat = 41,
            MetadataWebIngestion = 42,
            MetadataApiIngestion = 43,
            MetadataSpreadsheetIngestion = 44
        }

        public enum DataSharingEvent
        {
            DataSharingRequestCreated = 1,
            DataSharingRequestEdited = 2,
            DataSharingRequestUpdated = 3,
            DataSharingRequestDeleted = 4,
            DataSharingRequestSent = 5,
            DataSharingRequestReceived = 6,
            DataSharingRequestAccepted = 7,
            DataSharingRequestRejected = 8,
            DataSharingRequestCancelled = 9,
            DataSharingRequestCompleted = 10,
            DataSharingAlertSent = 11,
            DataSharingAlertReceived = 12,
            DataSharingAccessGranted = 13,
            DataSharingAccessRevoked = 14,
            DataSharingSettingsUpdated = 15,
            DataSharingComplianceCheckStarted = 16,
            DataSharingComplianceCheckPassed = 17,
            DataSharingComplianceCheckFailed = 18,
            DataSharingAuditLogged = 19,
            DataSharingAgreementUpdated = 20,
            DataSharingAgreementReturnedWithComments = 21,
            DataSharingSubmissionReview = 22,
            DataSharingSubmissionNotes = 23,
            DataSharingRequestReturned = 24,
            DataSharingRequestDownload = 25,
            DataSharingRequestNotification = 26
        }
        public enum MetadataEvent
        {
            MetadataSearchPerformed = 1,
            MetadataViewed = 2,
            MetadataEdited = 3,
            MetadataPublished = 4,
            MetadataCreated = 5,
            MetadataValidated = 6,
            MetadataReviewInitiated = 7,
            MetadataReviewCompleted = 8,
            MetadataReviewApproved = 9,
            MetadataReviewRejected = 10,
            MetadataDeleted = 11,
            MetadataAccessRequested = 12,
            MetadataAccessGranted = 13,
            MetadataAccessDenied = 14,
            MetadataDatasetCreated = 15,
            MetadataDatasetUpdated = 16,
            MetadataExportInitiated = 17,
            MetadataExportCompleted = 18,
            MetadataImportInitiated = 19,
            MetadataImportCompleted = 20,
            MetadataPublishedStatusChange = 21,
            MetadataStatusChange = 22,
            MetadataDatasetConflict = 23
        }
        public enum UserEvent
        {
            UserLogin = 1,
            UserLogout = 2,
            UserPageNavigation = 3,
            UserFailedLoginAttempt = 4,
            UserPasswordResetRequested = 5,
            UserPasswordResetCompleted = 6,
            UserRegistered = 7,
            UserProfileUpdated = 8,
            UserAccountDeleted = 9,
            UserAccountSuspended = 10,
            UserAccountReactivated = 11,
            UserProfileViewed = 12,
            UserSearch = 13,
            UserAccessDenied = 14,
            UserNotificationsUpdated = 15,
            UserAccessAllowed = 16,
            UserManagementPageAccess = 17,
            UserManageOrganisationPageAccess = 18,
            UserChangedAllowList = 20,
            UserRequestedPublisher = 21,
            UserManageApprovals = 22,
            UserApprovalApproved = 23,
            UserApprovalRejected = 24,
            UserDataShareRequestStart = 25,
            UserDataShareRequestEnd = 26,
            UserOpenedQuestion = 27,
            UserClosedQuestion = 28,
            UserSetQuestion = 29,
            UserSetQuestionAnswer = 30,
            UserSetQuestionAnswerInvalid = 31,
            UserMoveToNextQuestion = 32,
            UserSetQuestionAnswerCompleted = 33,

        }
        public enum ErrorEvent 
        { 
            None,
            ApplicationError,
            DatashareRequestError,
            ValidationError,
            AccessError
        }

        public enum ServiceSupportEvent
        {
            SupportRequestRaised = 1,
            SupportRequestAcknowledged = 2,
            SupportResponseProvided = 3,
            SupportRequestReassigned = 4,
            SupportRequestEscalated = 5,
            SupportRequestUpdated = 6,
            SupportRequestResolved = 7,
            SupportRequestClosed = 8,
            SupportRequestReopened = 9,
            UserFeedbackSubmitted = 10,
            SupportRequestCommentAdded = 11,
            SupportRequestDocumentationUpdated = 12,
            SupportRequestPriorityChanged = 13,
            SupportRequestStatusChanged = 14,
            SupportRequestCategoryChanged = 15,
            SupportRequestAssignedToTeam = 16,
            SupportRequestAssignedToIndividual = 17,
            SupportInteractionLogged = 18,
            SupportFollowUpScheduled = 19,
            SupportSolutionSuggested = 20,
            SupportTicketAuditLogged = 21,
            SupportRequestTagged = 22,
            SupportRequestUntagged = 23,
            SupportRequestOwnershipTransferred = 24,
            SupportRequestSatisfactionSurveySent = 25,
            SupportRequestSatisfactionSurveyCompleted = 26
        }
        public enum DeploymentAndMonitoringEvent
        {
            DeploymentInitiated = 1,
            DeploymentCompleted = 2,
            DeploymentFailed = 3,
            ServiceStarted = 4,
            ServiceStopped = 5,
            ServiceRestarted = 6,
            DeploymentRolledBack = 7,
            ServiceHealthCheckPassed = 8,
            ServiceHealthCheckFailed = 9,
            ServiceScaledUp = 10,
            ServiceScaledDown = 11,
            ConfigurationUpdated = 12,
            SecurityPatchApplied = 13,
            PerformanceTestStarted = 14,
            PerformanceTestCompleted = 15,
            LoadTestStarted = 16,
            LoadTestCompleted = 17,
            DeploymentVerified = 18,
            IncidentReported = 19,
            IncidentResolved = 20,
            MaintenanceWindowStarted = 21,
            MaintenanceWindowEnded = 22,
            BackupStarted = 23,
            BackupCompleted = 24,
            BackupFailed = 25,
            RecoveryProcessInitiated = 26,
            RecoveryProcessCompleted = 27,
            AlertRaised = 28,
            AlertResolved = 29,
            AlertAcknowledged = 30,
            VersionUpgradeInitiated = 31,
            VersionUpgradeCompleted = 32,
            VersionUpgradeRolledBack = 33,
            MonitoringServiceAdded = 34,
            MonitoringServiceRemoved = 35,
            CustomEventTriggered = 36,
            ServiceDependencyIssueDetected = 37,
            ServiceDependencyIssueResolved = 38,
            EnvironmentPreparationStarted = 39,
            EnvironmentPreparationCompleted = 40,
            StaticCodeAnalysisStarted = 41,
            StaticCodeAnalysisCompleted = 42,
            StaticCodeAnalysisPassed = 43,
            StaticCodeAnalysisFailed = 44,
            SecurityTestingStarted = 45,
            SecurityTestingCompleted = 46,
            SecurityTestPassed = 47,
            SecurityTestFailed = 48,
            AutomatedCompatibilityTestStarted = 49,
            AutomatedCompatibilityTestCompleted = 50,
            CompatibilityTestPassed = 51,
            CompatibilityTestFailed = 52,
            AccessibilityTestingStarted = 53,
            AccessibilityTestingCompleted = 54,
            AccessibilityTestPassed = 55,
            AccessibilityTestFailed = 56,
            PerformanceTestingPassed = 57,
            PerformanceTestingFailed = 58,
            AutomatedTestSuiteStarted = 59,
            AutomatedTestSuiteCompleted = 60,
            AutomatedTestSuitePassed = 61,
            AutomatedTestSuiteFailed = 62
        }

        public enum DeveloperApiEvents
        {
            Create = 1,
            UpdateName = 2,
            UpdateScope = 3,
            UpdateExpiry = 4,
            Revoked = 5,
            Error = 6
        }
    }
}
